-- local g = vim.g
-- local cmd = vim.cmd
-- g.gruvbox_material_background = "medium"
-- g.gruvbox_material_palette = "mix"
-- g.gruvbox_material_enable_bold = 1
-- g.gruvbox_material_diagnostic_virtual_text = "colored"
-- g.gruvbox_material_better_performance = 1
-- g.gruvbox_material_visual = "reverse"
-- cmd("colorscheme gruvbox-material")
-- cmd("colorscheme tokyonight")
